"""CLI command to configure Mimir hooks for popular agent CLIs.

Supported agents:
- kimi-code
- claude-code
- codex
- opencode

Each setup writes the minimal hook configuration needed to call Mimir's
``mimir_turn`` and ``skill_interceptor`` hooks on lifecycle events. The command
is idempotent: running it twice does not create duplicate hooks.
"""

from __future__ import annotations

import json
import shutil
import sys
from pathlib import Path
from typing import Any, Protocol


class AgentSetup(Protocol):
    """Install Mimir hooks for a specific agent CLI."""

    agent: str

    def __init__(self, base_dir: Path | None = None) -> None:
        pass

    def install(self) -> Path:
        """Write hook configuration and return the path written."""
        pass

    def is_installed(self) -> bool:
        """Return True if Mimir hooks are already configured."""
        pass


def _hook_command() -> str:
    """Return the shell command that invokes the Mimir turn hook."""
    python = shutil.which("python3") or shutil.which("python") or sys.executable
    return f'{python} -m mimir.hooks.mimir_turn --backend llama-server --base-url http://127.0.0.1:11435 --model all-MiniLM-L6-v2'


def _interceptor_command() -> str:
    """Return the shell command that invokes the Mimir skill interceptor hook."""
    python = shutil.which("python3") or shutil.which("python") or sys.executable
    return f'{python} -m mimir.hooks.skill_interceptor'


class KimiCodeSetup:
    """Append Mimir hooks to ``~/.kimi-code/config.toml``."""

    agent = "kimi-code"

    def __init__(self, home_dir: Path | None = None) -> None:
        self.home_dir = Path(home_dir or Path.home() / ".kimi-code")
        self.config_path = self.home_dir / "config.toml"

    def is_installed(self) -> bool:
        if not self.config_path.exists():
            return False
        text = self.config_path.read_text()
        return "mimir.hooks.mimir_turn" in text and "mimir.hooks.skill_interceptor" in text

    def install(self) -> Path:
        self.home_dir.mkdir(parents=True, exist_ok=True)
        command = _hook_command()
        interceptor_command = _interceptor_command()
        snippet = f"""\n# Mimir memory hooks (auto-generated by `mimir setup kimi-code`)\n[[hooks]]\nevent = "PreToolUse"\ncommand = "{interceptor_command}"\ntimeout = 5\n\n[[hooks]]\nevent = "UserPromptSubmit"\ncommand = "{command}"\ntimeout = 10\n\n[[hooks]]\nevent = "Stop"\ncommand = "{command}"\ntimeout = 10\n\n[[hooks]]\nevent = "SessionStart"\ncommand = "{command}"\ntimeout = 10\n"""
        if self.config_path.exists():
            existing = self.config_path.read_text()
            if "mimir.hooks.mimir_turn" in existing and "mimir.hooks.skill_interceptor" in existing:
                return self.config_path
            self.config_path.write_text(existing.rstrip() + "\n" + snippet, encoding="utf-8")
        else:
            self.config_path.write_text(snippet.lstrip(), encoding="utf-8")
        return self.config_path


class ClaudeCodeSetup:
    """Merge Mimir hooks into ``~/.claude/settings.json``."""

    agent = "claude-code"

    def __init__(self, config_dir: Path | None = None) -> None:
        self.config_dir = Path(config_dir or Path.home() / ".claude")
        self.settings_path = self.config_dir / "settings.json"

    def is_installed(self) -> bool:
        if not self.settings_path.exists():
            return False
        try:
            data = json.loads(self.settings_path.read_text())
        except json.JSONDecodeError:
            return False
        text = json.dumps(data)
        return "mimir_turn" in text and "skill_interceptor" in text

    def install(self) -> Path:
        self.config_dir.mkdir(parents=True, exist_ok=True)
        command = _hook_command()
        mimir_hook = {
            "matcher": "*",
            "hooks": [
                {
                    "type": "command",
                    "command": command,
                }
            ],
        }
        interceptor_command = _interceptor_command()
        interceptor_hook = {
            "matcher": "*",
            "hooks": [
                {
                    "type": "command",
                    "command": interceptor_command,
                }
            ],
        }
        if self.settings_path.exists():
            try:
                data = json.loads(self.settings_path.read_text())
            except json.JSONDecodeError:
                data = {}
        else:
            data = {}

        for event in ("PreToolUse", "UserPromptSubmit", "Stop", "SessionStart"):
            hooks = data.setdefault(event, [])
            target = interceptor_hook if event == "PreToolUse" else mimir_hook
            marker = "skill_interceptor" if event == "PreToolUse" else "mimir_turn"
            if not any(marker in json.dumps(h) for h in hooks):
                hooks.append(target)

        self.settings_path.write_text(json.dumps(data, indent=2), encoding="utf-8")
        return self.settings_path


class CodexSetup:
    """Append Mimir hooks to ``~/.codex/config.toml``."""

    agent = "codex"

    def __init__(self, home_dir: Path | None = None) -> None:
        self.home_dir = Path(home_dir or Path.home() / ".codex")
        self.config_path = self.home_dir / "config.toml"

    def is_installed(self) -> bool:
        if not self.config_path.exists():
            return False
        text = self.config_path.read_text()
        return "mimir.hooks.mimir_turn" in text and "mimir.hooks.skill_interceptor" in text

    def install(self) -> Path:
        self.home_dir.mkdir(parents=True, exist_ok=True)
        command = _hook_command()
        interceptor_command = _interceptor_command()
        snippet = f"""\n# Mimir memory hooks (auto-generated by `mimir setup codex`)\n[[PreToolUse]]\nmatcher = ".*"\n\n[[PreToolUse.hooks]]\ntype = "command"\ncommand = "{interceptor_command}"\ntimeout = 5\n\n[[UserPromptSubmit]]\nmatcher = ".*"\n\n[[UserPromptSubmit.hooks]]\ntype = "command"\ncommand = "{command}"\ntimeout = 10\n\n[[Stop]]\nmatcher = ".*"\n\n[[Stop.hooks]]\ntype = "command"\ncommand = "{command}"\ntimeout = 10\n\n[[SessionStart]]\nmatcher = ".*"\n\n[[SessionStart.hooks]]\ntype = "command"\ncommand = "{command}"\ntimeout = 10\n"""
        if self.config_path.exists():
            existing = self.config_path.read_text()
            if "mimir.hooks.mimir_turn" in existing and "mimir.hooks.skill_interceptor" in existing:
                return self.config_path
            self.config_path.write_text(existing.rstrip() + "\n" + snippet, encoding="utf-8")
        else:
            self.config_path.write_text(snippet.lstrip(), encoding="utf-8")
        return self.config_path


def _default_opencode_plugin_path() -> Path:
    """Return the default path to the bundled OpenCode plugin."""
    return Path(__file__).resolve().parents[2] / "plugins" / "opencode"


class OpenCodeSetup:
    """Add the Mimir plugin to OpenCode's ``~/.config/opencode/opencode.json``."""

    agent = "opencode"

    def __init__(
        self,
        config_dir: Path | None = None,
        plugin_path: Path | None = None,
    ) -> None:
        self.config_dir = Path(config_dir or Path.home() / ".config" / "opencode")
        self.config_path = self.config_dir / "opencode.json"
        self.plugin_path = Path(plugin_path or _default_opencode_plugin_path()).resolve()

    def _is_mimir_plugin(self, entry: Any) -> bool:
        """Return True if ``entry`` already points to the Mimir plugin."""
        if isinstance(entry, str):
            return "mimir-opencode-plugin" in entry or str(self.plugin_path) == entry
        if isinstance(entry, (list, tuple)) and len(entry) > 0:
            package = entry[0]
            return "mimir-opencode-plugin" in str(package) or str(self.plugin_path) == package
        if isinstance(entry, dict):
            package = entry.get("package", "")
            return "mimir-opencode-plugin" in str(package) or str(self.plugin_path) == package
        return False

    def is_installed(self) -> bool:
        if not self.config_path.exists():
            return False
        try:
            data = json.loads(self.config_path.read_text())
        except json.JSONDecodeError:
            return False
        plugins = data.get("plugin", [])
        return any(self._is_mimir_plugin(entry) for entry in plugins)

    def install(self) -> Path:
        self.config_dir.mkdir(parents=True, exist_ok=True)
        python = shutil.which("python3") or shutil.which("python") or sys.executable
        plugin_entry: list[Any] = [
            str(self.plugin_path),
            {
                "python": python,
                "backend": "llama-server",
                "baseUrl": "http://127.0.0.1:11435",
                "model": "all-MiniLM-L6-v2",
            },
        ]
        if self.config_path.exists():
            try:
                data = json.loads(self.config_path.read_text())
            except json.JSONDecodeError:
                data = {}
        else:
            data = {}

        # The correct OpenCode config key is the singular ``plugin``; remove any
        # stale ``plugins`` array we may have written in earlier versions.
        if isinstance(data.get("plugins"), list):
            del data["plugins"]

        plugins = data.setdefault("plugin", [])
        if not any(self._is_mimir_plugin(entry) for entry in plugins):
            plugins.append(plugin_entry)

        self.config_path.write_text(json.dumps(data, indent=2), encoding="utf-8")
        return self.config_path


SETUP_REGISTRY: dict[str, type[AgentSetup]] = {
    "kimi-code": KimiCodeSetup,
    "claude-code": ClaudeCodeSetup,
    "codex": CodexSetup,
    "opencode": OpenCodeSetup,
}


def list_supported_agents() -> list[str]:
    return list(SETUP_REGISTRY.keys())


def create_setup(agent: str, base_dir: Path | None = None) -> AgentSetup:
    setup_cls = SETUP_REGISTRY.get(agent)
    if setup_cls is None:
        raise ValueError(f"Unsupported agent: {agent}. Supported: {', '.join(SETUP_REGISTRY)}")
    return setup_cls(base_dir)
